### PR TITLE
Update addinganddeleting.md

### PR DESCRIPTION
**Pull request by cfjedimaster**
Three small typo fixes.

Signed-off-by: Raymond Camden <raymondcamden@gmail.com>

### CODE REVIEW

**Comment by olifink** [comment]
Thank you @cfjedimaster for your PR – notice that you did not sign off your commit so the DCO check fails (see also our CONTRIBUTING.md).
To sign off your PR is easy, I provided the commands below to update your branch cfjedimaster:patch-1

`git commit –amend` to the commit message body add the DCO sign-off- which I guess in your case is
`Signed-off-by:  Raymond Camden <your-email-here>`

`git push -f`

**Comment by cfjedimaster** [comment]
I did my PR via GitHub's edit feature - let me see if I can address this here as well.

**Comment by cfjedimaster** [comment]
Does that (the edit) work for you?

**Comment by olifink** [comment]
hmm, DCO robot is still complaining... can you try `git commit --amend --signoff`  and then `git push --force-with-lease origin patch-1`

**Comment by cfjedimaster** [comment]
Ok, I clone down my fork. `git commit --amend --signoff` worked. The second command failed with `error: src refspec patch-1 does not match any.` Sorry - my GitFu CLI skills are the bare minimum.

**Comment by olifink** [comment]
No worries, the sign-off is there and I waved it through. Sorry about the process & thanks for the PR 🙂

**Comment by cfjedimaster** [comment]
Thanks - I meant to get to this today - but the day got away.

**Pull request merged**
